### ISSUE TITLE
ios版的k线有问题

### ISSUE THREAD

**Issue by suangzhi** [coinx123/coinx-ios#1]
k线无法显示，只能显示三条均线，而且无法对k线进行放大和缩小；交易那个页面，bitmex的名字显示不全。

**Comment by bk97531** [comment]
只能显示三条均线是什么情况下的？k线目前还没支出放大缩小，后面会支持，能提供下币种和手机型号吗

**Comment by bk97531** [comment]
> k线无法显示，只能显示三条均线，而且无法对k线进行放大和缩小；交易那个页面，bitmex的名字显示不全。

只能显示三条均线是什么情况下的？k线目前还没支出放大缩小，后面会支持，能提供下币种和手机型号吗

**Comment by suangzhi** [comment]
显示如上图，用的是日版6s，莫非和这个有关系？应该不会吧

发自我的 iPhone

**Comment by bk97531** [comment]
> 显示如上图，用的是日版6s，莫非和这个有关系？应该不会吧 发自我的 iPhone
> […](#)
> 在 2019年1月19日，08:51，bk97531 ***@***.***> 写道： k线无法显示，只能显示三条均线，而且无法对k线进行放大和缩小；交易那个页面，bitmex的名字显示不全。 只能显示三条均线是什么情况下的？k线目前还没支出放大缩小，后面会支持，能提供下币种和手机型号吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

看不到图，你直接说币种名称，手机系统多少的，我这边看看能不能重现。

**Comment by suangzhi** [comment]
bitmex上面的所有币种都不能显示k线，只有三条均线，手机系统ios12.1.2（16c101）。

发自我的 iPhone

**Comment by bk97531** [comment]
你的三条均线是什么意思？本来k线ma就是三条，周的那个币种因为交易量的原因，在分时那里都是0所以是一条直线。

**Comment by suangzhi** [comment]
我换了个国行ip6也是无法显示，k线指的是柱状图

发自我的 iPhone

**Comment by bk97531** [comment]
> 我换了个国行ip6也是无法显示，k线指的是柱状图 发自我的 iPhone
> […](#)

你截个图发我邮箱吧cbk0822@163.com

**Comment by suangzhi** [comment]
已经发了2张截图，你看163邮箱收到没

发自我的 iPhone

**Comment by bk97531** [comment]
> 已经发了2张截图，你看163邮箱收到没 发自我的 iPhone
> […](#)

收到了，我这边看看什么原因，我们这边都是有显示的柱状图的

**Comment by suangzhi** [comment]
对了，交易页面的bitmex名字显示不全是因为我用的粗字体，换成系统默认的字体就完全显示了，其他问题暂时没有发现

发自我的 iPhone

**Comment by bk97531** [comment]
> 对了，交易页面的bitmex名字显示不全是因为我用的粗字体，换成系统默认的字体就完全显示了，其他问题暂时没有发现 发自我的 iPhone
> […](#)

嗯嗯，这边都修改了，后面会更新的
