### ISSUE TITLE
绑定交易失败

### ISSUE THREAD

**Issue by ghost** [coinx123/coinx-ios#2]
绑定交易所的时候提示Request timestamp expired

**Comment by ghost** [comment]
绑定交易所成功了，但是iOS版k线柱状图没显示，请问还会更新吗？

**Comment by deanMrZeng** [comment]
后期会更新




------------------ 原始邮件 ------------------
发件人: "seasonsv"<notifications@github.com>;
发送时间: 2019年5月26日(星期天) 中午11:40
收件人: "coinx123/coinx-ios"<coinx-ios@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [coinx123/coinx-ios] 绑定交易失败 (#2)




绑定交易所成功了，但是iOS版k线柱状图没显示，请问还会更新吗？
